### ISSUE TITLE
Category Product Position

### ISSUE THREAD

**Issue by emrahuyanik** [tappz/magento#1]
[https://github.com/tappz/magento/blob/master/app/code/community/TmobLabs/Tappz/Model/Catalog/Api.php](url)

I have changed getProductList function, 
reasons
1)We should get product collection from category because of "anchor categories"
2) The below code starts pagination from 1, so offset starts with pageSize, 
That means listing starts with page 2
`empty($pageNumber) ?    $pageNumber = 1 :  $pageNumber +=1;`
to
`empty($pageNumber) ?    $pageNumber = 0 :  $pageNumber +=1;`

3) Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH means "visible both category and search", this option id equals 4 for native magento.
But we should get 2,4 which means "Catalog" and "Catalog and Search" products to list in categories. 

You can find changed function below

  public function getProductList($phrase, $categoryId, $pageNumber, $pageSize, $filterQuery, $sort)
    {
        Mage::app()->setCurrentStore(1);
        // Mage::app()->setCurrentWebsite(1);
        if($categoryId){
            $layer = Mage::getModel('catalog/layer');
            $category = Mage::getModel("catalog/category")->load($categoryId);
            $layer->setCurrentCategory($category);
            $collection = $layer->getProductCollection()
            ->addAttributeToSelect('_');
            // $category = Mage::getModel("catalog/category")->load($categoryId);
            // $collection = $category->getProductCollection()
            // ->addAttributeToSelect('_')
            // ->addAttributeToFilter('status', '1')
            // ->addAttributeToFilter('visibility', Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH);
        }else{
            $collection = Mage::getModel('catalog/product')
            ->getCollection()
            ->addAttributeToSelect('*')
            ->addAttributeToFilter('status', '1')
            ->addAttributeToFilter('visibility', Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH);

```
    }
    if (!empty($filter)) {
        foreach ($filter as $f) {
            if (isset($f->selected)) {
                $collection->addAttributeToSelect($f->id)
                    ->addAttributeToFilter($f->id, $f->selected->id);
            }
        }
    }

    if (!empty($phrase))
        $collection->addAttributeToFilter('name', array('like' => "%$phrase%"));

    // if (!empty($categoryId)) {
        // $collection->joinField('category_id', 'catalog/category_product', 'category_id', 'product_id = entity_id', null, 'left');
        // $collection->addAttributeToFilter('category_id', array('eq' => $categoryId));
    // }

    $total = $collection->getSize();

    // $collection->addAttributeToSort('position', 'ASC');

     // $pageSize = 5;
    empty($pageNumber) ?    $pageNumber = 0 :  $pageNumber +=1;

    if (empty($pageSize))
        $pageSize = 6;

    if (!empty($sort)) {
        $sortArr = explode("-", $sort);
        $collection->addAttributeToSort($sortArr[0], $sortArr[1]);
    }elseif(is_numeric($categoryId)){
        $collection->getSelect()->order('cat_index_position', 'ASC');
    }
    $result = array();
    $result['total'] = null;
    $result['filters'] = array();
    $result['sortList'] = array();
    $result['products'] = array();
    $result['total'] = $total;
    $result['sortList'][] = array('id' => 'name-asc', 'name' => 'Ada Göre A – Z');
    $result['sortList'][] = array('id' => 'name-desc', 'name' => 'Ada Göre Z – A ');
    $result['sortList'][] = array('id' => 'price-asc', 'name' => 'Fiyata Göre Artan');
    $result['sortList'][] = array('id' => 'price-desc', 'name' => 'Fiyata Göre Azalan');

    if (!empty($collection)) {
        foreach ($collection as $_product) {
            $result['products'][] = $this->getProduct($_product->getId());
        }
    }
    return $result;
}
```

**Comment by dzgok** [comment]
Thank you for feedback and contribute.

> That means listing starts with page 2
> 
> empty($pageNumber) ? $pageNumber = 1 : $pageNumber +=1;
> 
> to
> 
> empty($pageNumber)? $pageNumber = 1 : $pageNumber +=1;

Both of them  is same.İ suppose you mean 
`empty($pageNumber)? $pageNumber = 1 : $pageNumber +=1;`
to 
`empty($pageNumber)? $pageNumber = 0 : $pageNumber +=1;
`
İf you want to use 'else if'  statement  on 

https://github.com/tappz/magento/blob/master/app/code/community/TmobLabs/Tappz/Model/Catalog/Api.php#L157 

then you should  change that lines.  

https://github.com/tappz/magento/blob/master/app/code/community/TmobLabs/Tappz/Model/Catalog/Api.php#L17

https://github.com/tappz/magento/blob/master/app/code/community/TmobLabs/Tappz/Model/Catalog/Api.php#L26
https://github.com/tappz/magento/blob/master/app/code/community/TmobLabs/Tappz/Model/Catalog/Api.php#L35
https://github.com/tappz/magento/blob/master/app/code/community/TmobLabs/Tappz/Model/Catalog/Api.php#L44

Best .

**Comment by dzgok** [comment]
https://github.com/tappz/magento/blob/master/app/code/community/TmobLabs/Tappz/Model/Catalog/Api.php#L124
